### ISSUE TITLE
Support coloured output

### ISSUE THREAD

**Issue by savchenko** [Canop/clima#14]
Measured colouring helps user to recognise key elements: headings, links, etc.
Would you consider optionally rendering those in colour?

**Comment by Canop** [comment]
What would you suggest ? Changing the skin in Clima ? Giving a skin like `clima --skin my/file.skin something.md` ?

**Comment by savchenko** [comment]
Yes, something along the lines of `clima --config rainbow.toml`. As an example, `rainbow.toml` could be:

```toml
[colours]
fg = "#ffffff"
bg = "#000000"
borders = "#3c3c3c"
h1 = "#ff8059"
h2 = "#44bc44"
h3 = "#d0bc00"
bold = ""
italic = ""
underline = ""
```

`borders` refers to the table borders, `<hr>` and similar elements.
Foreground, background and headings are self-explanatory.
Emphasized elements are assigned null strings, hence should be rendered as any other text.
